FROM debian:jessie

RUN apt-get update -y
RUN apt-get install -y libssl1.0.0 libsctp1

ENV LANG=C.UTF-8

COPY tini-static /sbin/tini-static

COPY rel /rel

ENV PORT=4000
EXPOSE 4000

ENTRYPOINT ["/sbin/tini-static", "--"]
CMD ["/rel/deploy_talk/bin/deploy_talk", "foreground"]
